export const SESSION_IDLE_TIMEOUT_SECONDS = 2 * 60 * 60;
export const SESSION_IDLE_TIMEOUT_MS = SESSION_IDLE_TIMEOUT_SECONDS * 1000;

export const SESSION_ABSOLUTE_TIMEOUT_SECONDS = 6 * 60 * 60;
export const SESSION_ABSOLUTE_TIMEOUT_MS =
  SESSION_ABSOLUTE_TIMEOUT_SECONDS * 1000;

export const SESSION_IDLE_CHECK_INTERVAL_MS = 60 * 1000;
export const SESSION_HEARTBEAT_INTERVAL_MS = 5 * 60 * 1000;
